version: "3"

services:

  apisix:
    build:
      context: ./..
      dockerfile: centos/Dockerfile
    restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - "80:9080/tcp"
      - "443:9443/tcp"
